apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
   name: aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:ap-southeast-1:689093831747:secret:app-test-secret-7NV9nJ"
        objectType: "secretsmanager"
        jmesPath:
          - path: variable4
            objectAlias: variable4
  secretObjects:
    - secretName: app-test-secret
      type: Opaque
      data:
      - objectName: app-test-secret
        key: variable4
# "arn:aws:secretsmanager:ap-southeast-1:689093831747:secret:app-test-secret-7NV9nJ"
