name: Deployment

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy environment'
        type: choice
        default: 'develop'
        options:
        - develop

jobs:
  push-registry:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build . -t practices-workflow:$(git describe --always --tag)
      # - name: Get secret
      #   env:
      #     SECRET_WORD: ${{ secrets.SECRET_WORD }}
      #     WORD: TEST_ENV
      #   run: ./test.bash && echo $WORD | git describe --always --tag
      # - name: Step 2 - GitHub Action if statement (true)
      #   env:
      #     WHO_TO_TRUST: ${{ secrets.SECRET_WORD }}
      #   if:  env.WHO_TO_TRUST == 'SECRET_WORD'
      #   run: echo "I know what the secret token is!"
