name: Action2

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]
jobs:
  Explore-GitHub-Actions1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Explore-GitHub-Actions1"
  Explore-GitHub-Actions2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Explore-GitHub-Actions2"
