name: Action1

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]
jobs:
  Actions1-Job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Actions1-Job1"
      - run: echo "Actions1-Job1 repeated
  Actions1-Job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Actions1-Job2"

  Actions1-Job3:
    needs: Actions1-Job1, Actions1-Job2
    runs-on: ubuntu-latest
    steps:
      - run: echo "Actions1-Job2"
